name: 🪂 Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types: [published, edited, prereleased]
  workflow_dispatch:

jobs:
  build-main:
    name: 🔨 Build and deploy default docker image
    uses: WGBH-MLA/.github/.github/workflows/build.yml@main

  build-arm:
    name: 🦾 Build and deploy arm64v8 docker image
    uses: WGBH-MLA/.github/.github/workflows/build.yml@buildx
    with:
      file: arm64.dockerfile
      buildx: true
      platforms: linux/arm64
      tags: |
        type=schedule,prefix=arm64-
        type=ref,event=branch,prefix=arm64-
        type=ref,event=tag,prefix=arm64-
        type=ref,event=pr,prefix=arm64-
